name: asciidoctor-ghpages
author: Manoel Campos da Silva Filho
branding:
  icon: book-open
  color: blue
description: Recursively converts every adoc file to html, renaming resulting README.html to index.html

inputs:
  asciidoctor_params:
    description: 'Extra parameters to passs to the asciidoctor command to customize the process of building adoc files'
    required: false
  adoc_file_ext:
    description: 'The extension you are using for your AsciiDoc Files'
    default: '.adoc'
    required: false

runs: 
  using: "composite"

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
  - name: Configure git
    run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    shell: bash

  - name: Asciidoctor Setup
    run: |
      sudo apt-get install gem -y
      sudo gem install asciidoctor
    shell: bash

  # Avoids keeping the commit history for the gh-pages branch, 
  # so that such a branch keeps only the last commit. 
  # But this slows down the GitHub Pages website build process.
  - name: Checking out the gh-pages branch without keeping its history
    run: |
      git branch -D gh-pages 1>/dev/null 2>/dev/null || true
      git log | head -n 1 | cut -d' ' -f2 > /tmp/commit-hash.txt
      git checkout --orphan gh-pages master 1>/dev/null
    shell: bash

  #- name: Checking out the gh-pages branch, keeping its history
  #  run: git checkout master -B gh-pages 1>/dev/null
  #  shell: bash  

  - name: Converting AsciiDoc files to HTML
    env: 
      INPUT_ASCIIDOCTOR_PARAMS: ${{ inputs.asciidoctor_params }}
      INPUT_ADOC_FILE_EXT: ${{ inputs.adoc_file_ext }}
    run: |
      if [[ $INPUT_ADOC_FILE_EXT != .* ]]; then 
          INPUT_ADOC_FILE_EXT=".$INPUT_ADOC_FILE_EXT"; 
      fi
      find . -name "*$INPUT_ADOC_FILE_EXT" | xargs asciidoctor -b html $INPUT_ASCIIDOCTOR_PARAMS
      for FILE in `find . -name "README.html"`; do 
          mv "$FILE" "`dirname $FILE`/index.html"; 
      done
      for FILE in `find . -name "*.html"`; do 
         git add -f "$FILE"; 
      done
      MSG="Build $INPUT_ADOC_FILE_EXT Files for GitHub Pages from commit `cat /tmp/commit-hash.txt`"
      echo $MSG
      find . -name "*$INPUT_ADOC_FILE_EXT" | xargs git rm -f
      git rm -rf .github/
      git commit -m "$MSG" 1>/dev/null 
      git push -f --quiet --set-upstream origin gh-pages 1>/dev/null 
    shell: bash
